# -*- coding: utf-8 -*-
"""guess_card_code.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-cl8RshG3TddJFaEEgOcznvR-T5JnhZ
"""

def guess_card_code(secret:int, attempts_left:int):
    #asks the player to guess code
    guess=(int(input("Guess the code!: ")))

    #checks if guess is correct/true
    if guess == secret:
       print("The old stones tremble... the gates creak open. You have succeeded.")
       return True
    # checks if it was last attempt(3 attempts)
    elif attempts_left== 1:
        print("The ancient gates remain sealed. The castle crumbles further into ruin...")
        return False
    #when guess number is too low
    elif guess < secret:
        print("The code fades too dimly... it is too low.")
        return guess_card_code(secret, attempts_left - 1)
    #when guess number is too high
    else:
        print("The code blazes too fiercely... it is too high")
        return guess_card_code(secret, attempts_left -1)

#starts game. 8 is the secret number and 3 is the amount of attempts
guess_card_code(8, 3)